spring.application.name=emanon
spring.config.import=file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=${SPRING_SECURITY_USER}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

jwt.issuer=${JWT_ISSUER}
jwt.secret=${JWT_SECRET}
jwt.expiration.access=${JWT_ACCESS_EXPIRATION_MS}
jwt.expiration.refresh=${JWT_REFRESH_EXPIRATION_MS}

cdn.storage.endpoint=${STORAGE_ENDPOINT:http://localhost:4566}
cdn.storage.region=${STORAGE_REGION:us-east-1}
cdn.storage.bucket=${STORAGE_BUCKET:emanon}
cdn.storage.presigned_url_expiration_seconds=${STORAGE_PRESIGNED_URL_EXPIRATION:300}
cdn.storage.profile_storage_path=${STORAGE_PROFILE_STORAGE_PATH:profile-pictures}

cdn.s3.access-key=${FLOCI_ACCESS_KEY:test}
cdn.s3.secret-key=${FLOCI_SECRET_KEY:test}