spring.application.name=emanon
spring.config.import=file:.env[.properties]

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.security.user.name=${SPRING_SECURITY_USER}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

jwt.issuer=${JWT_ISSUER}
jwt.secret=${JWT_SECRET}